server:
  port: 8080

spring:
  application:
    name: demo-erm
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_erm
    username: postgres
    password: Huy31102003

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml